name: mundig
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  bottom_navy_bar: ^6.0.0
  http: ^0.13.5
  translator: ^0.1.7
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  get_cli: ^0.2.30
  webviewx_plus: ^0.3.2
  font_awesome_flutter: ^10.4.0
  internet_connection_checker_plus: ^1.0.1
  connectivity_widget: ^1.0.0
  animated_widgets: ^1.1.0
  get_storage: ^2.1.1
  share_plus: ^6.3.1
  stroke_text: ^0.0.2
  url_launcher: ^6.1.10
  easy_splash_screen: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - pictures/default_country.png # The default country flag
    - pictures/no_result_en.png # No result picture english version
    - pictures/empty_en.png # List of favorites are empty english version
    - pictures/logo_mundig.png # Logo of the application
    - pictures/Africa.png
    - pictures/Americas.png
    - pictures/Antarctic.png
    - pictures/Asie.png
    - pictures/Europa.png
    - pictures/Oceania.png
